### ISSUE TITLE
Disable dirent reimplementation when POSIX dirent is available

### ISSUE THREAD

**Issue by cuckydev** [ValleyBell/SMPSPlay#11]
The dirent reimplementation has issues compiling without io.h, which seems to be some strange header provided by Microsoft, and is not at all available when compiling outside of Windows.

**Comment by ValleyBell** [comment]
Oops, I missed this when writing the CMakeLists file.
`dirent.c/.h` is only required for MSVC and I forgot to exclude it for GCC builds in the CMake project. (The Makefile doesn't build it.)

Anyway, it's fixed with 7da241e377c20433d96d870b4ed3a362fc149f97.
