### ISSUE TITLE
Any Way to Control Tempo?

### ISSUE THREAD

**Issue by Kurausukun** [ValleyBell/SMPSPlay#3]
Is there any way to change the tempo of the currently playing song? It's possible in Game Emu Player, so I figure it should be possible here, but I'm not sure. The end-goal of this is that I'd like to record an "in-game" version of the Blue Spheres theme from S3K that speeds up accordingly.

**Comment by ValleyBell** [comment]
I'm afraid SMPSPlay itself doesn't have such a feature. It just has a NTSC/PAL switch.

However, MainMemory wrote a tool called [SMPSTempo](https://github.com/MainMemory/SMPSTempo) that is able to [do that](https://www.youtube.com/watch?v=R3KSjhHhVLM).  
The tool makes use of the [SMPSOUT DLL](http://forums.sonicretro.org/index.php?showtopic=32918), which brings SMPS songs into S&K PC Collection and is based on an older version of SMPSPlay. It works really well for all those MegaDrive Sonic games though.

**Comment by Kurausukun** [comment]
I actually did find that a few minutes after posting that. Sorry to clutter the issues page, you can close this now. But I do have a question--where does SMPSTempo get the SMPS files it plays? I see some paths in the configuration file, but they don't seem to actually exist, so are the files baked into the exe or something?

**Comment by ValleyBell** [comment]
A way to control the tempo in SMPSPlay itself would probably be nice, but I have no idea how to make it useable from the console interface.

SMPSTempo it just a GUI for the SMPSOUT DLL. The SMPS songs and everything else related to SMPS emulation/playback is stored within the DLL. The configuration paths are only used when the DLL is compiled, I think.
