### ISSUE TITLE
Controls Are Broken

### ISSUE THREAD

**Issue by Kurausukun** [ValleyBell/SMPSPlay#4]
I feel like this might be an issue that Windows somehow introduced because I tried a previous version as well and had the same issues, but maybe you can help me troubleshoot anyway. The controls in the program seem pretty broken for some reason. For example, pressing down while a song is playing results in the program switching to PAL mode, and after any command is inputted, the whole program stops accepting any input and appears to freeze (music will continue to play, but the timer will stop). The only way out of this that I have found is hitting left or right. Can you reproduce this? I'm on the latest update for Windows 10.

**Comment by ValleyBell** [comment]
Weird ... it works fine for me in Windows 7 and Windows 10, version 1709. (I tested the 32-bit and 64-bit versions compiled with Visual Studio 2010.)

Did you use one of the .exe files I released on Sonic Retro or did you compile it by yourself. If it's the latter, what tools did you use?

**Comment by Kurausukun** [comment]
Both of the ones I tried were versions I compiled myself using VS 2017. I tested the version 2.11 build you posted on Sonic Retro, and it works fine, but I need a more recent build than that so I can take advantage of the volume configuration.

But I guess this means we can narrow it down to some issue with building it. Is there anything specific I should know about retargeting the solution, for example?

**Comment by ValleyBell** [comment]
I'll try to compile it with VS2017 in a few days. I don't have it at hand right now.

Meanwhile, could you try the v2.20 binary? You can find it [here](http://forums.sonicretro.org/index.php?showtopic=32473&view=findpost&p=929100). (Sorry, I forgot to update the OP, so it was pointing to the old v2.11 version. I updated it just now.)

**Comment by Kurausukun** [comment]
The version 2.20 build works fine. Thanks for that, by the way, I didn't know the pack had been updated since v4.

I guess the issue is something related to my compilation of it, then. I don't know if this is related, but I've never been able to compile a 64-bit executable of SMPSPlay that actually worked; it's not a problem because the 32-bit versions work fine, but the versions you built work fine. I'm assuming you built them with GCC and Msys then? I might try that and see if it works then.

**Comment by ValleyBell** [comment]
My setup is actually pretty interesting:  
Main development is done with VS2010 in 32-bit debug mode.  
I use Visual C++ 6.0 to compile the 32-bit executable, the 64-bit one is built with VS2010.  
The Makefile is used to build it on Linux, though MSYS/GCC works as well.

It's weird that building with VS2017 doesn't work properly and it's definitely something I want to investigate.

**Comment by Kurausukun** [comment]
I can't be 100% sure that it's VS2017; I tried using MinGW to compile it, but it proved to be a challenge. When attempting to build libvgm binaries, it couldn't find dsound.h, so I tried to find some DirectX SDK headers, but even then it threw errors with the headers, and I ended up giving up on it after around an hour of failing to build libvgm.

**Comment by ValleyBell** [comment]
I need to improve libvgm's build instructions then, I guess.  
You can find me in the [#vgmrips IRC](https://chat.mibbit.com/?url=irc%3A%2F%2Firc.digibase.ca%2Fvgmrips) if you want to chat.

**Comment by ValleyBell** [comment]
The non-working controls are caused by a [bug of the current Visual Studio runtime](https://developercommunity.visualstudio.com/content/problem/247770/-getch-broken-in-vs-157.html).

SMPSPlay handles the key sequence `0xE0 + key` (cursor keys) and `0x00 + key` (Alt + cursor keys) in a special way. Due to the bug it receives bad `0x00` characters.  
If you edit [this line](https://github.com/ValleyBell/SMPSPlay/blob/2c87fef8f1ddc9b19c9d830667093caef4dcfeef/src/main.c#L520) and disable the check for `inkey == 0x00` it works again - sort of. (You can't read any of the messages though, due to the additional key press that makes them vanish instantly.)

I guess I could just disable support for `Alt+key` combinations. I didn't use them anyway. (I actually intended Alt+cursor to behave the same as just pressing a cursor key, but this never worked due to the key codes being different in the Alt+ case.)

**Comment by Kurausukun** [comment]
Ah, okay. Good to know I wasn't actually doing anything wrong. I can just use 2.20 until this is fixed, although I'm still a bit bitter about how I was completely unable to build it with Msys, so I might come on IRC sometime and try again.

Thanks for investigating this, glad it was fruitful.
