### ISSUE TITLE
S3 Prototype

### ISSUE THREAD

**Issue by Kurausukun** [ValleyBell/SMPSPlay#8]
I know this isn't the place to ask this, and I'm really sorry, but I don't know where else to find you. I just wanted to ask if you were planning on releasing SMPS rips of the S3 prototype that recently surfaced, given that you added the commands to SMPSPlay, and where I should look for it if/when you do.

**Comment by ValleyBell** [comment]
So far I posted the rip on SSRG and Sonic Retro. (Not in the SMPSPlay topic, but in the S3 prototype discussion topics.)

**Comment by Kurausukun** [comment]
Thanks for that, I'll just close this then.
